Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,46 +1,63 @@
-name: SonarCloud Scan
+name: Terraform Code Scan
 
 on:
   push:
     branches:
-      - master  # Adjust branch name if needed
+      - master
   pull_request:
     branches:
-      - master  # Adjust branch name if needed
+      - master
 
 jobs:
-  sonarcloud_scan:
-    name: SonarCloud Scan
+  code_scan:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout Repository
+      - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set up JDK
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'
-          java-version: '11'
-
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v2
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: |
-            ${{ runner.os }}-sonar
-
-      - name: SonarCloud Scan
+      - name: Download and Install SonarScanner
         run: |
-          ./gradlew sonarqube \
-            -Dsonar.organization=ravisanchala123456 \
-            -Dsonar.projectKey=raviSanchala_PyMYSQL-class \
-            -Dsonar.host.url=https://sonarcloud.io \
-            -Dsonar.login=eceb47eddb02aae6f1122eff33d034afb61c8595
+          wget -q -O sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip"
+          unzip -q sonar-scanner.zip
+          ls -l
+          echo "-----"
+          ls -l sonar-scanner-4.7.0.2747-linux
+          echo "==="
+          ls -l sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner
+          chmod +x sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner
+          export PATH=/home/runner/work/PyMYSQL-class/sonar-scanner-4.7.0.2747-linux/bin/
+          echo "Hi:"
+          
+      - name: SonarQube Scan
+        run: |
+          /home/runner/work/PyMYSQL-class/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner --version
+          if [ $? -ne 0 ]; then
+            echo "SonarQube scan failed."
+            exit 1
+          fi
+        env:
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-      - name: Upload SonarCloud Quality Gate status
-        if: always()
+
+      - name: Upload SonarQube Analysis
         uses: github/codeql-action/upload-sarif@v1
         with:
+          sarif_file: ./sonarqube/out/sonar-project-*.sarif
+
+
+  sonarqube_scan:
+    name: SonarQube Scan
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checking out
+        uses: actions/checkout@v2
+        with:
+          # Disabling shallow clone is recommended for improving relevancy of reporting
+          fetch-depth: 0
+      - name: SonarQube Scan
+        uses: kitabisa/sonarqube-action@v1.2.0
+        with:
+          host: ${{ secrets.SONARQUBE_HOST }}
+          login: ${{ secrets.SONAR_TOKEN }}
+
           sarif_file: build/reports/sonar/sonar-report.json
